### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/dashboard-app#3]

**Comment by jenniferarnesen** [comment]
@jason-p-pickering What is our normal practice for indicating licensing for a repo? It seems that many of our frontend repos do not have a LICENSE file, but simply add the license property to package.json: ```"license": "BSD-3-Clause"```

In the dhis2-core repo, I do see the LICENSE file, but it doesn't specifically say which license type it is. For how it should be, see this link: https://choosealicense.com/licenses/bsd-3-clause/

So my thought is to do these 2 things:
1.  add a LICENSE file (according to https://choosealicense.com/licenses/bsd-3-clause/) and modify it with the HISP specific information that is in dhis2-core LICENSE file
2. modify package.json with the license property.

Here is the PR: https://github.com/dhis2/dashboards-app/pull/8
